name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  Firebase-App-Distribution:
    runs-on: ubuntu-latest
    steps:
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'keystore/your_signing_keystore.jks'
          encodedString: ${{ secrets.KEYSTORE }}

      - uses: actions/checkout@main
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
          
      - name: Update Secrets
        env:
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
          run: echo 'MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}' > ./local.properties

      - name: Build the Release AAB
        run: ./gradlew bundleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      
      - name: Firebase Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.5.0
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT}}
          file: app/build/outputs/bundle/release/app-release.aab
