name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  android_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Build the Release
        run: ./gradlew assembleRelease
      
      - name: Deploy to firebase
        uses: burhankhanzada/firebase_app_distribution_github_action@main
        with:
          service_account_key_json: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          app_id: ${{ secrets.FIREBASE_APP_ID }}
          app: app/build/outputs/apk/release/app-release-unsigned.apk
          groups: all
