name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  android_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build the Release
        run: ./gradlew assembleRelease

      - name: Upload Artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.5.0
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT}}
          file: app/build/outputs/apk/release/app-release-unsigned.apk
          debug: true
