name: Test and deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on: push

jobs:
  unit_tests:
    runs-on: [macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Unit tests
        run: ./gradlew testQa
