name: Unit test check

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  unit_tests:
    runs-on: [macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Unit tests
        run: ./gradlew testQa
