name: Unit test check

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  unit_tests:
    runs-on: [macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Update Secrets
        env:
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
        run: echo 'MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}' > ./local.properties
      - name: Unit tests
        run: ./gradlew testQa
